# Generated by tools/schema/generate.py; do not edit.
from __future__ import annotations

from typing import Literal, cast
from collections.abc import Mapping
from uuid import UUID
from datetime import date as Date
from .._records import Record, Unset, UNSET, FrozenJSONValue, JSONValue

Cardinality = Literal['one', 'many']
ClaimKind = Literal['sourced', 'asserted', 'derived']
CollectionKind = Literal['set', 'bag', 'sequence']
CompletionStatus = Literal['completed', 'limited', 'partial', 'failed', 'cancelled', 'skipped']
ContentKind = Literal['null', 'boolean', 'integer', 'float', 'string', 'uuid', 'date', 'datetime', 'time', 'duration', 'list', 'tuple', 'set', 'frozenset', 'mapping', 'mapping_proxy']
Depth = Literal['direct', 'transitive']
Direction = Literal['outgoing', 'incoming']
DomainKind = Literal['number', 'quantity', 'measurement', 'boolean', 'string', 'date', 'span', 'flow', 'stream', 'account', 'entity', 'collection']
DuplicateHandling = Literal['distinct', 'preserve']
EmptyHandling = Literal['error', 'zero']
ExpressionKind = Literal['quantity', 'boolean', 'reference', 'unary', 'binary', 'call', 'selection', 'query']
ImplementationKind = Literal['evaluator', 'compiler', 'solver']
MissingHandling = Literal['error', 'omit']
ObjectiveKind = Literal['minimize', 'maximize']
Operator = Literal['add', 'subtract', 'multiply', 'divide', 'equal', 'not_equal', 'less_than', 'less_than_or_equal', 'greater_than', 'greater_than_or_equal', 'power', 'negate', 'logical_not', 'logical_and', 'logical_or']
ParameterKind = Literal['positional_or_named', 'named_only']
ProjectionKind = Literal['entity', 'value']
ReconciliationStatus = Literal['provisional', 'confirmed']
SelectionKind = Literal['member', 'index']
Severity = Literal['info', 'warning', 'error']
SolutionStatus = Literal['feasible', 'infeasible', 'unknown', 'not_assessed', 'not_applicable']
StepKind = Literal['validation', 'formulation', 'solve', 'publication', 'selection']
TraversalKind = Literal['relationship', 'membership']
ValueKind = Literal['measurement', 'flow', 'property']
Content = FrozenJSONValue

class Argument(Record):
    __slots__ = ()
    _kind = 'Argument'

    def __init__(self, *,
        name: str,
        expression: Expression,
    ) -> None:
        self._initialize({
            'name': name,
            'expression': expression,
        })

    @property
    def name(self) -> str:
        return cast('str', self._field('name'))

    @property
    def expression(self) -> Expression:
        return cast('Expression', self._field('expression'))


class Entity(Record):
    __slots__ = ()
    _kind = 'Entity'

    def __init__(self, *,
        classification: UUID | None | Unset = UNSET,
        id: UUID,
        code: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        characteristics: Characteristics | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'classification': classification,
            'id': id,
            'code': code,
            'name': name,
            'characteristics': characteristics,
        })

    @property
    def classification(self) -> UUID | None:
        return cast('UUID | None', self._field('classification'))

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def code(self) -> str | None:
        return cast('str | None', self._field('code'))

    @property
    def name(self) -> str | None:
        return cast('str | None', self._field('name'))

    @property
    def characteristics(self) -> Characteristics | None:
        return cast('Characteristics | None', self._field('characteristics'))


class Assembly(Entity):
    __slots__ = ()
    _kind = 'Assembly'

    def __init__(self, *,
        entities: tuple[UUID, ...] | None | Unset = UNSET,
        relationships: tuple[UUID, ...] | None | Unset = UNSET,
        classification: UUID | None | Unset = UNSET,
        id: UUID,
        code: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        characteristics: Characteristics | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'entities': entities,
            'relationships': relationships,
            'classification': classification,
            'id': id,
            'code': code,
            'name': name,
            'characteristics': characteristics,
        })

    @property
    def entities(self) -> tuple[UUID, ...] | None:
        return cast('tuple[UUID, ...] | None', self._field('entities'))

    @property
    def relationships(self) -> tuple[UUID, ...] | None:
        return cast('tuple[UUID, ...] | None', self._field('relationships'))

    @property
    def classification(self) -> UUID | None:
        return cast('UUID | None', self._field('classification'))

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def code(self) -> str | None:
        return cast('str | None', self._field('code'))

    @property
    def name(self) -> str | None:
        return cast('str | None', self._field('name'))

    @property
    def characteristics(self) -> Characteristics | None:
        return cast('Characteristics | None', self._field('characteristics'))


class Assignment(Record):
    __slots__ = ()
    _kind = 'Assignment'

    def __init__(self, *,
        value: UUID,
        quantity: Quantity,
    ) -> None:
        self._initialize({
            'value': value,
            'quantity': quantity,
        })

    @property
    def value(self) -> UUID:
        return cast('UUID', self._field('value'))

    @property
    def quantity(self) -> Quantity:
        return cast('Quantity', self._field('quantity'))


class Binding(Record):
    __slots__ = ()
    _kind = 'Binding'

    def __init__(self, *,
        name: str,
        value: UUID,
    ) -> None:
        self._initialize({
            'name': name,
            'value': value,
        })

    @property
    def name(self) -> str:
        return cast('str', self._field('name'))

    @property
    def value(self) -> UUID:
        return cast('UUID', self._field('value'))


class Call(Record):
    __slots__ = ()
    _kind = 'Call'

    def __init__(self, *,
        function: UUID,
        arguments: tuple[Expression, ...] | None | Unset = UNSET,
        named_arguments: tuple[Argument, ...] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'function': function,
            'arguments': arguments,
            'named_arguments': named_arguments,
        })

    @property
    def function(self) -> UUID:
        return cast('UUID', self._field('function'))

    @property
    def arguments(self) -> tuple[Expression, ...] | None:
        return cast('tuple[Expression, ...] | None', self._field('arguments'))

    @property
    def named_arguments(self) -> tuple[Argument, ...] | None:
        return cast('tuple[Argument, ...] | None', self._field('named_arguments'))


class Characteristics(Record):
    __slots__ = ()
    _kind = 'Characteristics'

    def __init__(self, *,
        labels: tuple[Label, ...] | None | Unset = UNSET,
        values: tuple[Value, ...] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'labels': labels,
            'values': values,
        })

    @property
    def labels(self) -> tuple[Label, ...] | None:
        return cast('tuple[Label, ...] | None', self._field('labels'))

    @property
    def values(self) -> tuple[Value, ...] | None:
        return cast('tuple[Value, ...] | None', self._field('values'))


class Claim(Record):
    __slots__ = ()
    _kind = 'Claim'

    def __init__(self, *,
        id: UUID,
        content: JSONValue | None,
        kind: ClaimKind,
        sources: tuple[Location | UUID, ...] | None | Unset = UNSET,
        method: Method | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'id': id,
            'content': content,
            'kind': kind,
            'sources': sources,
            'method': method,
        })

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def content(self) -> FrozenJSONValue | None:
        return cast('FrozenJSONValue | None', self._field('content'))

    @property
    def kind(self) -> ClaimKind:
        return cast('ClaimKind', self._field('kind'))

    @property
    def sources(self) -> tuple[Location | UUID, ...] | None:
        return cast('tuple[Location | UUID, ...] | None', self._field('sources'))

    @property
    def method(self) -> Method | None:
        return cast('Method | None', self._field('method'))


class Classification(Record):
    __slots__ = ()
    _kind = 'Classification'

    def __init__(self, *,
        id: UUID,
        code: str,
        name: str,
        definition: str | None | Unset = UNSET,
        parent: UUID | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'id': id,
            'code': code,
            'name': name,
            'definition': definition,
            'parent': parent,
        })

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def code(self) -> str:
        return cast('str', self._field('code'))

    @property
    def name(self) -> str:
        return cast('str', self._field('name'))

    @property
    def definition(self) -> str | None:
        return cast('str | None', self._field('definition'))

    @property
    def parent(self) -> UUID | None:
        return cast('UUID | None', self._field('parent'))


class Constraint(Record):
    __slots__ = ()
    _kind = 'Constraint'

    def __init__(self, *,
        id: UUID,
        code: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        description: str | None | Unset = UNSET,
        predicate: UUID,
    ) -> None:
        self._initialize({
            'id': id,
            'code': code,
            'name': name,
            'description': description,
            'predicate': predicate,
        })

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def code(self) -> str | None:
        return cast('str | None', self._field('code'))

    @property
    def name(self) -> str | None:
        return cast('str | None', self._field('name'))

    @property
    def description(self) -> str | None:
        return cast('str | None', self._field('description'))

    @property
    def predicate(self) -> UUID:
        return cast('UUID', self._field('predicate'))


class ContentEntry(Record):
    __slots__ = ()
    _kind = 'ContentEntry'

    def __init__(self, *,
        key: PropertyContent,
        value: PropertyContent,
    ) -> None:
        self._initialize({
            'key': key,
            'value': value,
        })

    @property
    def key(self) -> PropertyContent:
        return cast('PropertyContent', self._field('key'))

    @property
    def value(self) -> PropertyContent:
        return cast('PropertyContent', self._field('value'))


class Criterion(Record):
    __slots__ = ()
    _kind = 'Criterion'

    def __init__(self, *,
        key: str,
        classification: UUID,
    ) -> None:
        self._initialize({
            'key': key,
            'classification': classification,
        })

    @property
    def key(self) -> str:
        return cast('str', self._field('key'))

    @property
    def classification(self) -> UUID:
        return cast('UUID', self._field('classification'))


class Definitions(Record):
    __slots__ = ()
    _kind = 'Definitions'

    def __init__(self, *,
        taxonomies: tuple[Taxonomy, ...] | None | Unset = UNSET,
        measures: tuple[Measure, ...] | None | Unset = UNSET,
        functions: tuple[Function, ...] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'taxonomies': taxonomies,
            'measures': measures,
            'functions': functions,
        })

    @property
    def taxonomies(self) -> tuple[Taxonomy, ...] | None:
        return cast('tuple[Taxonomy, ...] | None', self._field('taxonomies'))

    @property
    def measures(self) -> tuple[Measure, ...] | None:
        return cast('tuple[Measure, ...] | None', self._field('measures'))

    @property
    def functions(self) -> tuple[Function, ...] | None:
        return cast('tuple[Function, ...] | None', self._field('functions'))


class Diagnostic(Record):
    __slots__ = ()
    _kind = 'Diagnostic'

    def __init__(self, *,
        severity: Severity,
        code: str,
        message: str,
        document: UUID | Unset = UNSET,
        target: UUID | None | Unset = UNSET,
        residual: Quantity | Unset = UNSET,
        tolerance: Quantity | Unset = UNSET,
    ) -> None:
        self._initialize({
            'severity': severity,
            'code': code,
            'message': message,
            'document': document,
            'target': target,
            'residual': residual,
            'tolerance': tolerance,
        })

    @property
    def severity(self) -> Severity:
        return cast('Severity', self._field('severity'))

    @property
    def code(self) -> str:
        return cast('str', self._field('code'))

    @property
    def message(self) -> str:
        return cast('str', self._field('message'))

    @property
    def document(self) -> UUID | None:
        return cast('UUID | None', self._field('document'))

    @property
    def target(self) -> UUID | None:
        return cast('UUID | None', self._field('target'))

    @property
    def residual(self) -> Quantity | None:
        return cast('Quantity | None', self._field('residual'))

    @property
    def tolerance(self) -> Quantity | None:
        return cast('Quantity | None', self._field('tolerance'))


class Domain(Record):
    __slots__ = ()
    _kind = 'Domain'

    def __init__(self, *,
        kind: DomainKind,
        units: str | None | Unset = UNSET,
        measure: UUID | Unset = UNSET,
        item_domain: Domain | Unset = UNSET,
        collection_kind: CollectionKind | Unset = UNSET,
    ) -> None:
        self._initialize({
            'kind': kind,
            'units': units,
            'measure': measure,
            'item_domain': item_domain,
            'collection_kind': collection_kind,
        })

    @property
    def kind(self) -> DomainKind:
        return cast('DomainKind', self._field('kind'))

    @property
    def units(self) -> str | None:
        return cast('str | None', self._field('units'))

    @property
    def measure(self) -> UUID | None:
        return cast('UUID | None', self._field('measure'))

    @property
    def item_domain(self) -> Domain | None:
        return cast('Domain | None', self._field('item_domain'))

    @property
    def collection_kind(self) -> CollectionKind | None:
        return cast('CollectionKind | None', self._field('collection_kind'))


class Entry(Record):
    __slots__ = ()
    _kind = 'Entry'

    def __init__(self, *,
        key: str,
        value: str,
    ) -> None:
        self._initialize({
            'key': key,
            'value': value,
        })

    @property
    def key(self) -> str:
        return cast('str', self._field('key'))

    @property
    def value(self) -> str:
        return cast('str', self._field('value'))


class Expression(Record):
    __slots__ = ()
    _kind = 'Expression'

    def __init__(self, *,
        id: UUID,
        kind: ExpressionKind,
        quantity: Quantity | Unset = UNSET,
        boolean: bool | Unset = UNSET,
        target: UUID | Unset = UNSET,
        operator: Operator | Unset = UNSET,
        operands: tuple[Expression, ...] | None | Unset = UNSET,
        operand: Expression | Unset = UNSET,
        call: Call | Unset = UNSET,
        selection: Selection | Unset = UNSET,
        query: Query | Unset = UNSET,
    ) -> None:
        self._initialize({
            'id': id,
            'kind': kind,
            'quantity': quantity,
            'boolean': boolean,
            'target': target,
            'operator': operator,
            'operands': operands,
            'operand': operand,
            'call': call,
            'selection': selection,
            'query': query,
        })

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def kind(self) -> ExpressionKind:
        return cast('ExpressionKind', self._field('kind'))

    @property
    def quantity(self) -> Quantity | None:
        return cast('Quantity | None', self._field('quantity'))

    @property
    def boolean(self) -> bool | None:
        return cast('bool | None', self._field('boolean'))

    @property
    def target(self) -> UUID | None:
        return cast('UUID | None', self._field('target'))

    @property
    def operator(self) -> Operator | None:
        return cast('Operator | None', self._field('operator'))

    @property
    def operands(self) -> tuple[Expression, ...] | None:
        return cast('tuple[Expression, ...] | None', self._field('operands'))

    @property
    def operand(self) -> Expression | None:
        return cast('Expression | None', self._field('operand'))

    @property
    def call(self) -> Call | None:
        return cast('Call | None', self._field('call'))

    @property
    def selection(self) -> Selection | None:
        return cast('Selection | None', self._field('selection'))

    @property
    def query(self) -> Query | None:
        return cast('Query | None', self._field('query'))


class Fact(Record):
    __slots__ = ()
    _kind = 'Fact'

    def __init__(self, *,
        target: UUID,
        claims: tuple[UUID, ...],
        reconciliation: Reconciliation | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'target': target,
            'claims': claims,
            'reconciliation': reconciliation,
        })

    @property
    def target(self) -> UUID:
        return cast('UUID', self._field('target'))

    @property
    def claims(self) -> tuple[UUID, ...]:
        return cast('tuple[UUID, ...]', self._field('claims'))

    @property
    def reconciliation(self) -> Reconciliation | None:
        return cast('Reconciliation | None', self._field('reconciliation'))


class Filter(Record):
    __slots__ = ()
    _kind = 'Filter'

    def __init__(self, *,
        classification: UUID | Unset = UNSET,
        labels: tuple[Criterion, ...] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'classification': classification,
            'labels': labels,
        })

    @property
    def classification(self) -> UUID | None:
        return cast('UUID | None', self._field('classification'))

    @property
    def labels(self) -> tuple[Criterion, ...] | None:
        return cast('tuple[Criterion, ...] | None', self._field('labels'))


class Flow(Record):
    __slots__ = ()
    _kind = 'Flow'

    def __init__(self, *,
        units: str,
        movements: tuple[Movement, ...],
    ) -> None:
        self._initialize({
            'units': units,
            'movements': movements,
        })

    @property
    def units(self) -> str:
        return cast('str', self._field('units'))

    @property
    def movements(self) -> tuple[Movement, ...]:
        return cast('tuple[Movement, ...]', self._field('movements'))


class Formulation(Record):
    __slots__ = ()
    _kind = 'Formulation'

    def __init__(self, *,
        id: UUID,
        code: str | None | Unset = UNSET,
        name: str | None | Unset = UNSET,
        description: str | None | Unset = UNSET,
        bindings: tuple[Binding, ...] | None | Unset = UNSET,
        values: tuple[Value, ...] | None | Unset = UNSET,
        expressions: tuple[Expression, ...] | None | Unset = UNSET,
        constraints: tuple[Constraint, ...] | None | Unset = UNSET,
        formulations: tuple[Formulation, ...] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'id': id,
            'code': code,
            'name': name,
            'description': description,
            'bindings': bindings,
            'values': values,
            'expressions': expressions,
            'constraints': constraints,
            'formulations': formulations,
        })

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def code(self) -> str | None:
        return cast('str | None', self._field('code'))

    @property
    def name(self) -> str | None:
        return cast('str | None', self._field('name'))

    @property
    def description(self) -> str | None:
        return cast('str | None', self._field('description'))

    @property
    def bindings(self) -> tuple[Binding, ...] | None:
        return cast('tuple[Binding, ...] | None', self._field('bindings'))

    @property
    def values(self) -> tuple[Value, ...] | None:
        return cast('tuple[Value, ...] | None', self._field('values'))

    @property
    def expressions(self) -> tuple[Expression, ...] | None:
        return cast('tuple[Expression, ...] | None', self._field('expressions'))

    @property
    def constraints(self) -> tuple[Constraint, ...] | None:
        return cast('tuple[Constraint, ...] | None', self._field('constraints'))

    @property
    def formulations(self) -> tuple[Formulation, ...] | None:
        return cast('tuple[Formulation, ...] | None', self._field('formulations'))


class Function(Record):
    __slots__ = ()
    _kind = 'Function'

    def __init__(self, *,
        id: UUID,
        code: str,
        name: str,
        version: str,
        parameters: tuple[Parameter, ...] | None | Unset = UNSET,
        result: Domain,
        semantics: str,
        unit_rule: str,
        empty_collection: EmptyHandling | Unset = UNSET,
    ) -> None:
        self._initialize({
            'id': id,
            'code': code,
            'name': name,
            'version': version,
            'parameters': parameters,
            'result': result,
            'semantics': semantics,
            'unit_rule': unit_rule,
            'empty_collection': empty_collection,
        })

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def code(self) -> str:
        return cast('str', self._field('code'))

    @property
    def name(self) -> str:
        return cast('str', self._field('name'))

    @property
    def version(self) -> str:
        return cast('str', self._field('version'))

    @property
    def parameters(self) -> tuple[Parameter, ...] | None:
        return cast('tuple[Parameter, ...] | None', self._field('parameters'))

    @property
    def result(self) -> Domain:
        return cast('Domain', self._field('result'))

    @property
    def semantics(self) -> str:
        return cast('str', self._field('semantics'))

    @property
    def unit_rule(self) -> str:
        return cast('str', self._field('unit_rule'))

    @property
    def empty_collection(self) -> EmptyHandling | None:
        return cast('EmptyHandling | None', self._field('empty_collection'))


class Implementation(Record):
    __slots__ = ()
    _kind = 'Implementation'

    def __init__(self, *,
        kind: ImplementationKind,
        name: str,
        version: str,
    ) -> None:
        self._initialize({
            'kind': kind,
            'name': name,
            'version': version,
        })

    @property
    def kind(self) -> ImplementationKind:
        return cast('ImplementationKind', self._field('kind'))

    @property
    def name(self) -> str:
        return cast('str', self._field('name'))

    @property
    def version(self) -> str:
        return cast('str', self._field('version'))


class Label(Record):
    __slots__ = ()
    _kind = 'Label'

    def __init__(self, *,
        id: UUID,
        key: str,
        classifications: tuple[UUID, ...] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'id': id,
            'key': key,
            'classifications': classifications,
        })

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def key(self) -> str:
        return cast('str', self._field('key'))

    @property
    def classifications(self) -> tuple[UUID, ...] | None:
        return cast('tuple[UUID, ...] | None', self._field('classifications'))


class Location(Record):
    __slots__ = ()
    _kind = 'Location'

    def __init__(self, *,
        source: UUID,
        address: Mapping[str, Mapping[str, JSONValue] | str] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'source': source,
            'address': address,
        })

    @property
    def source(self) -> UUID:
        return cast('UUID', self._field('source'))

    @property
    def address(self) -> Mapping[str, Mapping[str, FrozenJSONValue] | str] | None:
        return cast('Mapping[str, Mapping[str, FrozenJSONValue] | str] | None', self._field('address'))


class Measure(Record):
    __slots__ = ()
    _kind = 'Measure'

    def __init__(self, *,
        id: UUID,
        code: str,
        name: str,
        units: str,
        definition: str | None | Unset = UNSET,
        tags: tuple[str, ...] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'id': id,
            'code': code,
            'name': name,
            'units': units,
            'definition': definition,
            'tags': tags,
        })

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def code(self) -> str:
        return cast('str', self._field('code'))

    @property
    def name(self) -> str:
        return cast('str', self._field('name'))

    @property
    def units(self) -> str:
        return cast('str', self._field('units'))

    @property
    def definition(self) -> str | None:
        return cast('str | None', self._field('definition'))

    @property
    def tags(self) -> tuple[str, ...] | None:
        return cast('tuple[str, ...] | None', self._field('tags'))


class Measurement(Record):
    __slots__ = ()
    _kind = 'Measurement'

    def __init__(self, *,
        measure: UUID,
        quantity: Quantity | None | Unset = UNSET,
        id: UUID,
    ) -> None:
        self._initialize({
            'measure': measure,
            'quantity': quantity,
            'id': id,
        })

    @property
    def measure(self) -> UUID:
        return cast('UUID', self._field('measure'))

    @property
    def quantity(self) -> Quantity | None:
        return cast('Quantity | None', self._field('quantity'))

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))


class Metadata(Record):
    __slots__ = ()
    _kind = 'Metadata'

    def __init__(self, *,
        id: UUID,
        schema_version: str,
        name: str | None | Unset = UNSET,
        description: str | None | Unset = UNSET,
        previous: UUID | Unset = UNSET,
    ) -> None:
        self._initialize({
            'id': id,
            'schema_version': schema_version,
            'name': name,
            'description': description,
            'previous': previous,
        })

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def schema_version(self) -> str:
        return cast('str', self._field('schema_version'))

    @property
    def name(self) -> str | None:
        return cast('str | None', self._field('name'))

    @property
    def description(self) -> str | None:
        return cast('str | None', self._field('description'))

    @property
    def previous(self) -> UUID | None:
        return cast('UUID | None', self._field('previous'))


class Method(Record):
    __slots__ = ()
    _kind = 'Method'

    def __init__(self, *,
        code: str,
        version: str | None | Unset = UNSET,
        description: str | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'code': code,
            'version': version,
            'description': description,
        })

    @property
    def code(self) -> str:
        return cast('str', self._field('code'))

    @property
    def version(self) -> str | None:
        return cast('str | None', self._field('version'))

    @property
    def description(self) -> str | None:
        return cast('str | None', self._field('description'))


class Model(Record):
    __slots__ = ()
    _kind = 'Model'

    def __init__(self, *,
        metadata: Metadata,
        definitions: Definitions | Unset = UNSET,
        system: System | Unset = UNSET,
        provenance: Provenance | Unset = UNSET,
    ) -> None:
        self._initialize({
            'metadata': metadata,
            'definitions': definitions,
            'system': system,
            'provenance': provenance,
        })

    @property
    def metadata(self) -> Metadata:
        return cast('Metadata', self._field('metadata'))

    @property
    def definitions(self) -> Definitions | None:
        return cast('Definitions | None', self._field('definitions'))

    @property
    def system(self) -> System | None:
        return cast('System | None', self._field('system'))

    @property
    def provenance(self) -> Provenance | None:
        return cast('Provenance | None', self._field('provenance'))


class Movement(Record):
    __slots__ = ()
    _kind = 'Movement'

    def __init__(self, *,
        key: str,
        date: Date | None | Unset = UNSET,
        period: Period | None | Unset = UNSET,
        magnitude: int | float | None | Unset = UNSET,
        claims: tuple[UUID, ...] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'key': key,
            'date': date,
            'period': period,
            'magnitude': magnitude,
            'claims': claims,
        })

    @property
    def key(self) -> str:
        return cast('str', self._field('key'))

    @property
    def date(self) -> Date | None:
        return cast('Date | None', self._field('date'))

    @property
    def period(self) -> Period | None:
        return cast('Period | None', self._field('period'))

    @property
    def magnitude(self) -> int | float | None:
        return cast('int | float | None', self._field('magnitude'))

    @property
    def claims(self) -> tuple[UUID, ...] | None:
        return cast('tuple[UUID, ...] | None', self._field('claims'))


class Objective(Record):
    __slots__ = ()
    _kind = 'Objective'

    def __init__(self, *,
        expression: UUID,
        sense: ObjectiveKind,
    ) -> None:
        self._initialize({
            'expression': expression,
            'sense': sense,
        })

    @property
    def expression(self) -> UUID:
        return cast('UUID', self._field('expression'))

    @property
    def sense(self) -> ObjectiveKind:
        return cast('ObjectiveKind', self._field('sense'))


class Parameter(Record):
    __slots__ = ()
    _kind = 'Parameter'

    def __init__(self, *,
        name: str,
        domain: Domain,
        kind: ParameterKind,
        required: bool,
    ) -> None:
        self._initialize({
            'name': name,
            'domain': domain,
            'kind': kind,
            'required': required,
        })

    @property
    def name(self) -> str:
        return cast('str', self._field('name'))

    @property
    def domain(self) -> Domain:
        return cast('Domain', self._field('domain'))

    @property
    def kind(self) -> ParameterKind:
        return cast('ParameterKind', self._field('kind'))

    @property
    def required(self) -> bool:
        return cast('bool', self._field('required'))


class Period(Record):
    __slots__ = ()
    _kind = 'Period'

    def __init__(self, *,
        start: Date,
        end: Date,
    ) -> None:
        self._initialize({
            'start': start,
            'end': end,
        })

    @property
    def start(self) -> Date:
        return cast('Date', self._field('start'))

    @property
    def end(self) -> Date:
        return cast('Date', self._field('end'))


class Projection(Record):
    __slots__ = ()
    _kind = 'Projection'

    def __init__(self, *,
        kind: ProjectionKind,
        key: str | Unset = UNSET,
        measure: UUID | Unset = UNSET,
        cardinality: Cardinality | Unset = UNSET,
        missing: MissingHandling | Unset = UNSET,
    ) -> None:
        self._initialize({
            'kind': kind,
            'key': key,
            'measure': measure,
            'cardinality': cardinality,
            'missing': missing,
        })

    @property
    def kind(self) -> ProjectionKind:
        return cast('ProjectionKind', self._field('kind'))

    @property
    def key(self) -> str | None:
        return cast('str | None', self._field('key'))

    @property
    def measure(self) -> UUID | None:
        return cast('UUID | None', self._field('measure'))

    @property
    def cardinality(self) -> Cardinality | None:
        return cast('Cardinality | None', self._field('cardinality'))

    @property
    def missing(self) -> MissingHandling | None:
        return cast('MissingHandling | None', self._field('missing'))


class PropertyContent(Record):
    __slots__ = ()
    _kind = 'PropertyContent'

    def __init__(self, *,
        kind: ContentKind,
        text: str | None | Unset = UNSET,
        zone: str | None | Unset = UNSET,
        fold: int | None | Unset = UNSET,
        items: tuple[PropertyContent, ...] | None | Unset = UNSET,
        entries: tuple[ContentEntry, ...] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'kind': kind,
            'text': text,
            'zone': zone,
            'fold': fold,
            'items': items,
            'entries': entries,
        })

    @property
    def kind(self) -> ContentKind:
        return cast('ContentKind', self._field('kind'))

    @property
    def text(self) -> str | None:
        return cast('str | None', self._field('text'))

    @property
    def zone(self) -> str | None:
        return cast('str | None', self._field('zone'))

    @property
    def fold(self) -> int | None:
        return cast('int | None', self._field('fold'))

    @property
    def items(self) -> tuple[PropertyContent, ...] | None:
        return cast('tuple[PropertyContent, ...] | None', self._field('items'))

    @property
    def entries(self) -> tuple[ContentEntry, ...] | None:
        return cast('tuple[ContentEntry, ...] | None', self._field('entries'))


class Provenance(Record):
    __slots__ = ()
    _kind = 'Provenance'

    def __init__(self, *,
        sources: tuple[Source, ...] | None | Unset = UNSET,
        claims: tuple[Claim, ...] | None | Unset = UNSET,
        facts: tuple[Fact, ...] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'sources': sources,
            'claims': claims,
            'facts': facts,
        })

    @property
    def sources(self) -> tuple[Source, ...] | None:
        return cast('tuple[Source, ...] | None', self._field('sources'))

    @property
    def claims(self) -> tuple[Claim, ...] | None:
        return cast('tuple[Claim, ...] | None', self._field('claims'))

    @property
    def facts(self) -> tuple[Fact, ...] | None:
        return cast('tuple[Fact, ...] | None', self._field('facts'))


class Quantity(Record):
    __slots__ = ()
    _kind = 'Quantity'

    def __init__(self, *,
        magnitude: int | float,
        units: str,
    ) -> None:
        self._initialize({
            'magnitude': magnitude,
            'units': units,
        })

    @property
    def magnitude(self) -> int | float:
        return cast('int | float', self._field('magnitude'))

    @property
    def units(self) -> str:
        return cast('str', self._field('units'))


class Query(Record):
    __slots__ = ()
    _kind = 'Query'

    def __init__(self, *,
        starting_at: UUID,
        steps: tuple[Traversal, ...] | None | Unset = UNSET,
        filter: Filter | Unset = UNSET,
        projection: Projection,
        duplicates: DuplicateHandling,
    ) -> None:
        self._initialize({
            'starting_at': starting_at,
            'steps': steps,
            'filter': filter,
            'projection': projection,
            'duplicates': duplicates,
        })

    @property
    def starting_at(self) -> UUID:
        return cast('UUID', self._field('starting_at'))

    @property
    def steps(self) -> tuple[Traversal, ...] | None:
        return cast('tuple[Traversal, ...] | None', self._field('steps'))

    @property
    def filter(self) -> Filter | None:
        return cast('Filter | None', self._field('filter'))

    @property
    def projection(self) -> Projection:
        return cast('Projection', self._field('projection'))

    @property
    def duplicates(self) -> DuplicateHandling:
        return cast('DuplicateHandling', self._field('duplicates'))


class Reconciliation(Record):
    __slots__ = ()
    _kind = 'Reconciliation'

    def __init__(self, *,
        selected: UUID,
        status: ReconciliationStatus,
        method: Method | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'selected': selected,
            'status': status,
            'method': method,
        })

    @property
    def selected(self) -> UUID:
        return cast('UUID', self._field('selected'))

    @property
    def status(self) -> ReconciliationStatus:
        return cast('ReconciliationStatus', self._field('status'))

    @property
    def method(self) -> Method | None:
        return cast('Method | None', self._field('method'))


class Relationship(Record):
    __slots__ = ()
    _kind = 'Relationship'

    def __init__(self, *,
        classification: UUID,
        id: UUID,
        source: UUID,
        target: UUID,
        characteristics: Characteristics | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'classification': classification,
            'id': id,
            'source': source,
            'target': target,
            'characteristics': characteristics,
        })

    @property
    def classification(self) -> UUID:
        return cast('UUID', self._field('classification'))

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def source(self) -> UUID:
        return cast('UUID', self._field('source'))

    @property
    def target(self) -> UUID:
        return cast('UUID', self._field('target'))

    @property
    def characteristics(self) -> Characteristics | None:
        return cast('Characteristics | None', self._field('characteristics'))


class Report(Record):
    __slots__ = ()
    _kind = 'Report'

    def __init__(self, *,
        status: Status,
        runtime: Runtime | Unset = UNSET,
        diagnostics: tuple[Diagnostic, ...] | None | Unset = UNSET,
        trace: tuple[Step, ...] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'status': status,
            'runtime': runtime,
            'diagnostics': diagnostics,
            'trace': trace,
        })

    @property
    def status(self) -> Status:
        return cast('Status', self._field('status'))

    @property
    def runtime(self) -> Runtime | None:
        return cast('Runtime | None', self._field('runtime'))

    @property
    def diagnostics(self) -> tuple[Diagnostic, ...] | None:
        return cast('tuple[Diagnostic, ...] | None', self._field('diagnostics'))

    @property
    def trace(self) -> tuple[Step, ...] | None:
        return cast('tuple[Step, ...] | None', self._field('trace'))


class Run(Record):
    __slots__ = ()
    _kind = 'Run'

    def __init__(self, *,
        metadata: Metadata,
        specification: UUID,
        spawns: tuple[UUID, ...] | None | Unset = UNSET,
        outputs: tuple[UUID, ...] | None | Unset = UNSET,
        report: Report,
    ) -> None:
        self._initialize({
            'metadata': metadata,
            'specification': specification,
            'spawns': spawns,
            'outputs': outputs,
            'report': report,
        })

    @property
    def metadata(self) -> Metadata:
        return cast('Metadata', self._field('metadata'))

    @property
    def specification(self) -> UUID:
        return cast('UUID', self._field('specification'))

    @property
    def spawns(self) -> tuple[UUID, ...] | None:
        return cast('tuple[UUID, ...] | None', self._field('spawns'))

    @property
    def outputs(self) -> tuple[UUID, ...] | None:
        return cast('tuple[UUID, ...] | None', self._field('outputs'))

    @property
    def report(self) -> Report:
        return cast('Report', self._field('report'))


class Runtime(Record):
    __slots__ = ()
    _kind = 'Runtime'

    def __init__(self, *,
        started_at: str | None | Unset = UNSET,
        finished_at: str | None | Unset = UNSET,
        implementations: tuple[Implementation, ...],
        settings: Settings | Unset = UNSET,
    ) -> None:
        self._initialize({
            'started_at': started_at,
            'finished_at': finished_at,
            'implementations': implementations,
            'settings': settings,
        })

    @property
    def started_at(self) -> str | None:
        return cast('str | None', self._field('started_at'))

    @property
    def finished_at(self) -> str | None:
        return cast('str | None', self._field('finished_at'))

    @property
    def implementations(self) -> tuple[Implementation, ...]:
        return cast('tuple[Implementation, ...]', self._field('implementations'))

    @property
    def settings(self) -> Settings | None:
        return cast('Settings | None', self._field('settings'))


class Selection(Record):
    __slots__ = ()
    _kind = 'Selection'

    def __init__(self, *,
        kind: SelectionKind,
        base: Expression,
        member: str | None | Unset = UNSET,
        index: Expression | Unset = UNSET,
    ) -> None:
        self._initialize({
            'kind': kind,
            'base': base,
            'member': member,
            'index': index,
        })

    @property
    def kind(self) -> SelectionKind:
        return cast('SelectionKind', self._field('kind'))

    @property
    def base(self) -> Expression:
        return cast('Expression', self._field('base'))

    @property
    def member(self) -> str | None:
        return cast('str | None', self._field('member'))

    @property
    def index(self) -> Expression | None:
        return cast('Expression | None', self._field('index'))


class Settings(Record):
    __slots__ = ()
    _kind = 'Settings'

    def __init__(self, *,
        relative_tolerance: int | float | None | Unset = UNSET,
        iteration_limit: int | None | Unset = UNSET,
        time_limit: int | float | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'relative_tolerance': relative_tolerance,
            'iteration_limit': iteration_limit,
            'time_limit': time_limit,
        })

    @property
    def relative_tolerance(self) -> int | float | None:
        return cast('int | float | None', self._field('relative_tolerance'))

    @property
    def iteration_limit(self) -> int | None:
        return cast('int | None', self._field('iteration_limit'))

    @property
    def time_limit(self) -> int | float | None:
        return cast('int | float | None', self._field('time_limit'))


class Source(Record):
    __slots__ = ()
    _kind = 'Source'

    def __init__(self, *,
        id: UUID,
        name: str,
        checksum: str,
        issued_at: Date | str | None | Unset = UNSET,
        received_at: Date | str | None | Unset = UNSET,
        author: str | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'id': id,
            'name': name,
            'checksum': checksum,
            'issued_at': issued_at,
            'received_at': received_at,
            'author': author,
        })

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def name(self) -> str:
        return cast('str', self._field('name'))

    @property
    def checksum(self) -> str:
        return cast('str', self._field('checksum'))

    @property
    def issued_at(self) -> Date | str | None:
        return cast('Date | str | None', self._field('issued_at'))

    @property
    def received_at(self) -> Date | str | None:
        return cast('Date | str | None', self._field('received_at'))

    @property
    def author(self) -> str | None:
        return cast('str | None', self._field('author'))


class Span(Period):
    __slots__ = ()
    _kind = 'Span'

    def __init__(self, *,
        name: str | None | Unset = UNSET,
        start: Date,
        end: Date,
    ) -> None:
        self._initialize({
            'name': name,
            'start': start,
            'end': end,
        })

    @property
    def name(self) -> str | None:
        return cast('str | None', self._field('name'))

    @property
    def start(self) -> Date:
        return cast('Date', self._field('start'))

    @property
    def end(self) -> Date:
        return cast('Date', self._field('end'))


class Specification(Record):
    __slots__ = ()
    _kind = 'Specification'

    def __init__(self, *,
        metadata: Metadata,
        model: UUID | Unset = UNSET,
        includes: tuple[UUID, ...] | None | Unset = UNSET,
        cases: tuple[UUID, ...] | None | Unset = UNSET,
        assignments: tuple[Assignment, ...] | None | Unset = UNSET,
        unknowns: tuple[UUID, ...] | None | Unset = UNSET,
        estimates: tuple[Assignment, ...] | None | Unset = UNSET,
        formulations: tuple[Formulation, ...] | None | Unset = UNSET,
        objectives: tuple[Objective, ...] | None | Unset = UNSET,
        settings: Settings | Unset = UNSET,
    ) -> None:
        self._initialize({
            'metadata': metadata,
            'model': model,
            'includes': includes,
            'cases': cases,
            'assignments': assignments,
            'unknowns': unknowns,
            'estimates': estimates,
            'formulations': formulations,
            'objectives': objectives,
            'settings': settings,
        })

    @property
    def metadata(self) -> Metadata:
        return cast('Metadata', self._field('metadata'))

    @property
    def model(self) -> UUID | None:
        return cast('UUID | None', self._field('model'))

    @property
    def includes(self) -> tuple[UUID, ...] | None:
        return cast('tuple[UUID, ...] | None', self._field('includes'))

    @property
    def cases(self) -> tuple[UUID, ...] | None:
        return cast('tuple[UUID, ...] | None', self._field('cases'))

    @property
    def assignments(self) -> tuple[Assignment, ...] | None:
        return cast('tuple[Assignment, ...] | None', self._field('assignments'))

    @property
    def unknowns(self) -> tuple[UUID, ...] | None:
        return cast('tuple[UUID, ...] | None', self._field('unknowns'))

    @property
    def estimates(self) -> tuple[Assignment, ...] | None:
        return cast('tuple[Assignment, ...] | None', self._field('estimates'))

    @property
    def formulations(self) -> tuple[Formulation, ...] | None:
        return cast('tuple[Formulation, ...] | None', self._field('formulations'))

    @property
    def objectives(self) -> tuple[Objective, ...] | None:
        return cast('tuple[Objective, ...] | None', self._field('objectives'))

    @property
    def settings(self) -> Settings | None:
        return cast('Settings | None', self._field('settings'))


class Status(Record):
    __slots__ = ()
    _kind = 'Status'

    def __init__(self, *,
        completion: CompletionStatus,
        solution: SolutionStatus,
    ) -> None:
        self._initialize({
            'completion': completion,
            'solution': solution,
        })

    @property
    def completion(self) -> CompletionStatus:
        return cast('CompletionStatus', self._field('completion'))

    @property
    def solution(self) -> SolutionStatus:
        return cast('SolutionStatus', self._field('solution'))


class Step(Record):
    __slots__ = ()
    _kind = 'Step'

    def __init__(self, *,
        kind: StepKind,
        at: str | None | Unset = UNSET,
        message: str,
        document: UUID | Unset = UNSET,
        target: UUID | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'kind': kind,
            'at': at,
            'message': message,
            'document': document,
            'target': target,
        })

    @property
    def kind(self) -> StepKind:
        return cast('StepKind', self._field('kind'))

    @property
    def at(self) -> str | None:
        return cast('str | None', self._field('at'))

    @property
    def message(self) -> str:
        return cast('str', self._field('message'))

    @property
    def document(self) -> UUID | None:
        return cast('UUID | None', self._field('document'))

    @property
    def target(self) -> UUID | None:
        return cast('UUID | None', self._field('target'))


class System(Record):
    __slots__ = ()
    _kind = 'System'

    def __init__(self, *,
        entities: tuple[Entity, ...] | None | Unset = UNSET,
        relationships: tuple[Relationship, ...] | None | Unset = UNSET,
        assemblies: tuple[Assembly, ...] | None | Unset = UNSET,
        formulations: tuple[Formulation, ...] | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'entities': entities,
            'relationships': relationships,
            'assemblies': assemblies,
            'formulations': formulations,
        })

    @property
    def entities(self) -> tuple[Entity, ...] | None:
        return cast('tuple[Entity, ...] | None', self._field('entities'))

    @property
    def relationships(self) -> tuple[Relationship, ...] | None:
        return cast('tuple[Relationship, ...] | None', self._field('relationships'))

    @property
    def assemblies(self) -> tuple[Assembly, ...] | None:
        return cast('tuple[Assembly, ...] | None', self._field('assemblies'))

    @property
    def formulations(self) -> tuple[Formulation, ...] | None:
        return cast('tuple[Formulation, ...] | None', self._field('formulations'))


class Taxonomy(Record):
    __slots__ = ()
    _kind = 'Taxonomy'

    def __init__(self, *,
        id: UUID,
        code: str,
        name: str,
        definition: str | None | Unset = UNSET,
        classifications: tuple[Classification, ...],
    ) -> None:
        self._initialize({
            'id': id,
            'code': code,
            'name': name,
            'definition': definition,
            'classifications': classifications,
        })

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def code(self) -> str:
        return cast('str', self._field('code'))

    @property
    def name(self) -> str:
        return cast('str', self._field('name'))

    @property
    def definition(self) -> str | None:
        return cast('str | None', self._field('definition'))

    @property
    def classifications(self) -> tuple[Classification, ...]:
        return cast('tuple[Classification, ...]', self._field('classifications'))


class Traversal(Record):
    __slots__ = ()
    _kind = 'Traversal'

    def __init__(self, *,
        kind: TraversalKind,
        depth: Depth,
        classification: UUID | Unset = UNSET,
        direction: Direction | Unset = UNSET,
    ) -> None:
        self._initialize({
            'kind': kind,
            'depth': depth,
            'classification': classification,
            'direction': direction,
        })

    @property
    def kind(self) -> TraversalKind:
        return cast('TraversalKind', self._field('kind'))

    @property
    def depth(self) -> Depth:
        return cast('Depth', self._field('depth'))

    @property
    def classification(self) -> UUID | None:
        return cast('UUID | None', self._field('classification'))

    @property
    def direction(self) -> Direction | None:
        return cast('Direction | None', self._field('direction'))


class Value(Record):
    __slots__ = ()
    _kind = 'Value'

    def __init__(self, *,
        measure: UUID | None | Unset = UNSET,
        quantity: Quantity | None | Unset = UNSET,
        id: UUID,
        key: str,
        kind: ValueKind,
        description: str | None | Unset = UNSET,
        flow: Flow | None | Unset = UNSET,
        content: PropertyContent | None | Unset = UNSET,
    ) -> None:
        self._initialize({
            'measure': measure,
            'quantity': quantity,
            'id': id,
            'key': key,
            'kind': kind,
            'description': description,
            'flow': flow,
            'content': content,
        })

    @property
    def measure(self) -> UUID | None:
        return cast('UUID | None', self._field('measure'))

    @property
    def quantity(self) -> Quantity | None:
        return cast('Quantity | None', self._field('quantity'))

    @property
    def id(self) -> UUID:
        return cast('UUID', self._field('id'))

    @property
    def key(self) -> str:
        return cast('str', self._field('key'))

    @property
    def kind(self) -> ValueKind:
        return cast('ValueKind', self._field('kind'))

    @property
    def description(self) -> str | None:
        return cast('str | None', self._field('description'))

    @property
    def flow(self) -> Flow | None:
        return cast('Flow | None', self._field('flow'))

    @property
    def content(self) -> PropertyContent | None:
        return cast('PropertyContent | None', self._field('content'))


_TYPES = {
    'Argument': Argument,
    'Assembly': Assembly,
    'Assignment': Assignment,
    'Binding': Binding,
    'Call': Call,
    'Characteristics': Characteristics,
    'Claim': Claim,
    'Classification': Classification,
    'Constraint': Constraint,
    'ContentEntry': ContentEntry,
    'Criterion': Criterion,
    'Definitions': Definitions,
    'Diagnostic': Diagnostic,
    'Domain': Domain,
    'Entity': Entity,
    'Entry': Entry,
    'Expression': Expression,
    'Fact': Fact,
    'Filter': Filter,
    'Flow': Flow,
    'Formulation': Formulation,
    'Function': Function,
    'Implementation': Implementation,
    'Label': Label,
    'Location': Location,
    'Measure': Measure,
    'Measurement': Measurement,
    'Metadata': Metadata,
    'Method': Method,
    'Model': Model,
    'Movement': Movement,
    'Objective': Objective,
    'Parameter': Parameter,
    'Period': Period,
    'Projection': Projection,
    'PropertyContent': PropertyContent,
    'Provenance': Provenance,
    'Quantity': Quantity,
    'Query': Query,
    'Reconciliation': Reconciliation,
    'Relationship': Relationship,
    'Report': Report,
    'Run': Run,
    'Runtime': Runtime,
    'Selection': Selection,
    'Settings': Settings,
    'Source': Source,
    'Span': Span,
    'Specification': Specification,
    'Status': Status,
    'Step': Step,
    'System': System,
    'Taxonomy': Taxonomy,
    'Traversal': Traversal,
    'Value': Value,
}

__all__ = ['Argument', 'Assembly', 'Assignment', 'Binding', 'Call', 'Cardinality', 'Characteristics', 'Claim', 'ClaimKind', 'Classification', 'CollectionKind', 'CompletionStatus', 'Constraint', 'Content', 'ContentEntry', 'ContentKind', 'Criterion', 'Definitions', 'Depth', 'Diagnostic', 'Direction', 'Domain', 'DomainKind', 'DuplicateHandling', 'EmptyHandling', 'Entity', 'Entry', 'Expression', 'ExpressionKind', 'Fact', 'Filter', 'Flow', 'Formulation', 'Function', 'Implementation', 'ImplementationKind', 'Label', 'Location', 'Measure', 'Measurement', 'Metadata', 'Method', 'MissingHandling', 'Model', 'Movement', 'Objective', 'ObjectiveKind', 'Operator', 'Parameter', 'ParameterKind', 'Period', 'Projection', 'ProjectionKind', 'PropertyContent', 'Provenance', 'Quantity', 'Query', 'Reconciliation', 'ReconciliationStatus', 'Relationship', 'Report', 'Run', 'Runtime', 'Selection', 'SelectionKind', 'Settings', 'Severity', 'SolutionStatus', 'Source', 'Span', 'Specification', 'Status', 'Step', 'StepKind', 'System', 'Taxonomy', 'Traversal', 'TraversalKind', 'Value', 'ValueKind']
