# Generated by tools/schema/generate.py; do not edit.
from enum import Enum, unique

@unique
class ActionKind(Enum):
    ASSIGN = 'assign'
    TERMINATE = 'terminate'

@unique
class Cardinality(Enum):
    ONE = 'one'
    MANY = 'many'

@unique
class ClaimKind(Enum):
    SOURCED = 'sourced'
    ASSERTED = 'asserted'
    DERIVED = 'derived'

@unique
class CollectionKind(Enum):
    SET = 'set'
    BAG = 'bag'
    SEQUENCE = 'sequence'

@unique
class CompletionStatus(Enum):
    COMPLETED = 'completed'
    LIMITED = 'limited'
    PARTIAL = 'partial'
    FAILED = 'failed'
    CANCELLED = 'cancelled'
    SKIPPED = 'skipped'

@unique
class ContentKind(Enum):
    NULL = 'null'
    BOOLEAN = 'boolean'
    INTEGER = 'integer'
    FLOAT = 'float'
    STRING = 'string'
    UUID = 'uuid'
    DATE = 'date'
    DATETIME = 'datetime'
    TIME = 'time'
    DURATION = 'duration'
    LIST = 'list'
    TUPLE = 'tuple'
    SET = 'set'
    FROZENSET = 'frozenset'
    MAPPING = 'mapping'
    MAPPING_PROXY = 'mapping_proxy'

@unique
class Depth(Enum):
    DIRECT = 'direct'
    TRANSITIVE = 'transitive'

@unique
class Direction(Enum):
    OUTGOING = 'outgoing'
    INCOMING = 'incoming'

@unique
class DistributionFamily(Enum):
    UNIFORM = 'uniform'
    TRIANGULAR = 'triangular'
    PERT = 'pert'

@unique
class DomainKind(Enum):
    NUMBER = 'number'
    QUANTITY = 'quantity'
    MEASUREMENT = 'measurement'
    BOOLEAN = 'boolean'
    STRING = 'string'
    DATE = 'date'
    SPAN = 'span'
    FLOW = 'flow'
    STREAM = 'stream'
    ACCOUNT = 'account'
    ENTITY = 'entity'
    COLLECTION = 'collection'

@unique
class DuplicateHandling(Enum):
    DISTINCT = 'distinct'
    PRESERVE = 'preserve'

@unique
class EmptyHandling(Enum):
    ERROR = 'error'
    ZERO = 'zero'

@unique
class ExpressionKind(Enum):
    QUANTITY = 'quantity'
    BOOLEAN = 'boolean'
    REFERENCE = 'reference'
    UNARY = 'unary'
    BINARY = 'binary'
    CALL = 'call'
    SELECTION = 'selection'
    QUERY = 'query'

@unique
class ImplementationKind(Enum):
    EVALUATOR = 'evaluator'
    COMPILER = 'compiler'
    SOLVER = 'solver'

@unique
class MissingHandling(Enum):
    ERROR = 'error'
    OMIT = 'omit'

@unique
class ObjectiveKind(Enum):
    MINIMIZE = 'minimize'
    MAXIMIZE = 'maximize'

@unique
class Operator(Enum):
    ADD = 'add'
    SUBTRACT = 'subtract'
    MULTIPLY = 'multiply'
    DIVIDE = 'divide'
    EQUAL = 'equal'
    NOT_EQUAL = 'not_equal'
    LESS_THAN = 'less_than'
    LESS_THAN_OR_EQUAL = 'less_than_or_equal'
    GREATER_THAN = 'greater_than'
    GREATER_THAN_OR_EQUAL = 'greater_than_or_equal'
    POWER = 'power'
    NEGATE = 'negate'
    LOGICAL_NOT = 'logical_not'
    LOGICAL_AND = 'logical_and'
    LOGICAL_OR = 'logical_or'

@unique
class ParameterKind(Enum):
    POSITIONAL_OR_NAMED = 'positional_or_named'
    NAMED_ONLY = 'named_only'

@unique
class ProjectionKind(Enum):
    ENTITY = 'entity'
    VALUE = 'value'

@unique
class ReconciliationStatus(Enum):
    PROVISIONAL = 'provisional'
    CONFIRMED = 'confirmed'

@unique
class SelectionKind(Enum):
    MEMBER = 'member'
    INDEX = 'index'

@unique
class Severity(Enum):
    INFO = 'info'
    WARNING = 'warning'
    ERROR = 'error'

@unique
class SolutionStatus(Enum):
    FEASIBLE = 'feasible'
    INFEASIBLE = 'infeasible'
    UNKNOWN = 'unknown'
    NOT_ASSESSED = 'not_assessed'
    NOT_APPLICABLE = 'not_applicable'

@unique
class StepKind(Enum):
    VALIDATION = 'validation'
    FORMULATION = 'formulation'
    SOLVE = 'solve'
    PUBLICATION = 'publication'
    SELECTION = 'selection'

@unique
class TraversalKind(Enum):
    RELATIONSHIP = 'relationship'
    MEMBERSHIP = 'membership'

@unique
class ValueKind(Enum):
    MEASUREMENT = 'measurement'
    FLOW = 'flow'
    PROPERTY = 'property'

_ENUM_TYPES = {
    'ActionKind': ActionKind,
    'Cardinality': Cardinality,
    'ClaimKind': ClaimKind,
    'CollectionKind': CollectionKind,
    'CompletionStatus': CompletionStatus,
    'ContentKind': ContentKind,
    'Depth': Depth,
    'Direction': Direction,
    'DistributionFamily': DistributionFamily,
    'DomainKind': DomainKind,
    'DuplicateHandling': DuplicateHandling,
    'EmptyHandling': EmptyHandling,
    'ExpressionKind': ExpressionKind,
    'ImplementationKind': ImplementationKind,
    'MissingHandling': MissingHandling,
    'ObjectiveKind': ObjectiveKind,
    'Operator': Operator,
    'ParameterKind': ParameterKind,
    'ProjectionKind': ProjectionKind,
    'ReconciliationStatus': ReconciliationStatus,
    'SelectionKind': SelectionKind,
    'Severity': Severity,
    'SolutionStatus': SolutionStatus,
    'StepKind': StepKind,
    'TraversalKind': TraversalKind,
    'ValueKind': ValueKind,
}

__all__ = ['ActionKind', 'Cardinality', 'ClaimKind', 'CollectionKind', 'CompletionStatus', 'ContentKind', 'Depth', 'Direction', 'DistributionFamily', 'DomainKind', 'DuplicateHandling', 'EmptyHandling', 'ExpressionKind', 'ImplementationKind', 'MissingHandling', 'ObjectiveKind', 'Operator', 'ParameterKind', 'ProjectionKind', 'ReconciliationStatus', 'SelectionKind', 'Severity', 'SolutionStatus', 'StepKind', 'TraversalKind', 'ValueKind']
