<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <TargetExt>.gha</TargetExt><AssemblyName>Rangekeeper.Components</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RhinoResources Condition="'$(RhinoResources)'==''">/Applications/Rhino 8.app/Contents/Frameworks/RhCore.framework/Versions/A/Resources</RhinoResources>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Canonical/*.cs" />
    <ProjectReference Include="../Model/Model.csproj" />
    <Reference Include="RhinoCommon"><HintPath>$(RhinoResources)/RhinoCommon.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Grasshopper"><HintPath>$(RhinoResources)/ManagedPlugIns/GrasshopperPlugin.rhp/Grasshopper.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="GH_IO"><HintPath>$(RhinoResources)/ManagedPlugIns/GrasshopperPlugin.rhp/GH_IO.dll</HintPath><Private>false</Private></Reference>
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>
</Project>
