# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Rangekeeper
author: Daniel Fink
copyright: '2023'
logo: resources/rangekeeper.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 6000

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/daniel-fink/rangekeeper  # Online location of your book
  path_to_book: walkthrough  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Add Executable Notebook support:
launch_buttons:
  colab_url: "https://colab.research.google.com"

sphinx:
  config:
    language: en
    html_extra_path: ['assets']
#    suppress_warnings: [ "mystnb.unknown_mime_type" ]  # See https://github.com/executablebooks/jupyter-book/issues/1950
#    html_js_files:
#      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js  # See https://jupyterbook.org/en/stable/interactive/interactive.html


